version: "3.3"
services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_USER: cribuser
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 3306
      DB_HOST: db
      DB_NAME: cribblydb
      FIREBASE_PROJ_ID: ${FIREBASE_PROJ_ID}
    command: ["dotnet", "CribblyBackend.dll"]

  db:
    image: "mysql:5.7"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: cribblydb
      MYSQL_USER: cribuser
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "32000:3306"

volumes:
  db_data:
